name: bigquery

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ADAPTER: bigquery
      BIGQUERY_PROJECT_ID: ${{ secrets.BIGQUERY_PROJECT_ID }}
      BIGQUERY_TEST_SERVICE_ACCOUNT_JSON: ${{ secrets.BIGQUERY_TEST_SERVICE_ACCOUNT_JSON }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8.10"
      - name: Copy credentials
        run: |
          printenv BIGQUERY_TEST_SERVICE_ACCOUNT_JSON >/home/runner/work/dbt-playbook/dbt-playbook/credentials.json
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest dbt-core dbt-bigquery
      - name: Run tests
        run: |
          pytest
