# The working directory is always:
# /home/runner/work/dbt-playbook/dbt-playbook/

name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres_db
          POSTGRES_PASSWORD: password
          POSTGRES_USER: user
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8.10"
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client
      - name: Query database
        run: psql -h localhost -d postgres_db -U user -c 'SELECT 1;'
        env:
          PGPASSWORD: password
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install dbt-core dbt-postgres
      - name: Run tests
        run: |
          pytest
